# Generated by Django 5.1.5 on 2026-02-01 20:46

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration: 0001_initial already creates User with country, phone_number,
    timezone, marketing_opt_in, terms_accepted_at. This migration originally
    added those fields; they were folded into 0001. Skip DB ops to avoid
    "duplicate column name: country" on fresh migrate.
    """

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Columns already exist from 0001
            state_operations=[],  # State already has these from 0001 CreateModel
        ),
    ]
