# Generated by Django 6.0.1 on 2026-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_verified_alter_user_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("learner", "Learner"),
                    ("org_admin", "Org Admin"),
                    ("instructor", "Instructor"),
                    ("finance", "Finance"),
                    ("tasc_admin", "TASC Admin"),
                    ("lms_manager", "LMS Manager"),
                ],
                default="learner",
                max_length=30,
            ),
        ),
    ]
