# Generated by Django 5.1.5 on 2026-02-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_set_password",
            field=models.BooleanField(default=False),
        ),
    ]
