# Generated by Django 5.1.5 on 2026-02-19 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_failed_login_attempts_account_locked_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginOTPChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("send_count", models.PositiveSmallIntegerField(default=1)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_otp_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_used"],
                        name="accounts_lo_user_id_0e3993_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_lo_expires_54ed8a_idx"
                    ),
                ],
            },
        ),
    ]
