# Generated by Django 5.1.5 on 2026-03-04 07:04

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_login_otp_challenge"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.AccountUserManager()),
            ],
        ),
    ]
