# Generated by Django 5.1.5 on 2026-03-17 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_add_assignment_model'),
        ('learning', '0003_add_submission_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.JSONField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user_activity', 'User Activity'), ('course_performance', 'Course Performance'), ('enrollment', 'Enrollment'), ('completion', 'Completion'), ('assessment', 'Assessment'), ('revenue', 'Revenue')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='learning_su_enrollm_1090ad_idx',
            old_name='learning_su_enrollm_a4d3a6_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='learning_su_assignm_860b09_idx',
            old_name='learning_su_assignm_c8f2b1_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='learning_su_status_02fa95_idx',
            old_name='learning_su_status_2e8a9c_idx',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='learning.enrollment'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='catalogue.quiz'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizsubmission'),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['enrollment', 'quiz'], name='learning_qu_enrollm_5b5abe_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['quiz', 'submitted_at'], name='learning_qu_quiz_id_244184_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['submission', 'question'], name='learning_qu_submiss_05a994_idx'),
        ),
    ]
