# Generated by Django 5.1.5 on 2026-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_quizquestion_explanation'),
        ('learning', '0004_quizanswer_quizsubmission_report_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('enrollment', 'assignment', 'attempt_number')},
        ),
    ]
