# Generated by Django 5.1.5 on 2026-03-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_submission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, default='')),
                ('category', models.CharField(choices=[('course_completion', 'Course Completion'), ('enrollment', 'Enrollment Milestones'), ('subscription', 'Subscription Loyalty'), ('assessment', 'Assessment Excellence'), ('engagement', 'Engagement'), ('milestone', 'Milestones')], max_length=50)),
                ('criteria_type', models.CharField(max_length=50)),
                ('criteria_value', models.IntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='learning.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='learning_us_user_id_62a63e_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
