# Generated by Django 5.1.5 on 2026-04-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_workshop_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionprogress',
            name='video_position_seconds',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
