# Generated by Django 5.1.5 on 2026-05-02 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_sessionprogress_video_position_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden pending moderator review'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden pending moderator review'),
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscussionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abusive', 'Abusive or Offensive Language'), ('off_topic', 'Off-Topic'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='learning.discussion')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='learning.discussionreply')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'discussion'), ('reporter', 'reply')},
            },
        ),
    ]
