# Generated by Django 5.1.5 on 2026-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_add_discussion_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='denial_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='approved', max_length=10),
        ),
    ]
