# Generated by Django 5.1.5 on 2026-02-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_paymentwebhook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("UGX", "Ugandan Shilling")],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("flutterwave", "Flutterwave")], max_length=20
            ),
        ),
    ]
