# Generated by Django 5.1.5 on 2026-03-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_currency_alter_payment_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesapalIPN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ipn_id", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField()),
                ("notification_type", models.CharField(default="GET", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("demo", "Demo / Sandbox"),
                            ("live", "Live / Production"),
                        ],
                        default="demo",
                        max_length=10,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Pesapal IPN",
                "verbose_name_plural": "Pesapal IPNs",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("UGX", "Ugandan Shilling"),
                    ("KES", "Kenyan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(choices=[("pesapal", "Pesapal")], max_length=20),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("bank_account", "Bank Account"),
                ],
                max_length=20,
            ),
        ),
    ]
