# Generated by Cursor (manual) as part of subscription-only Phase 1 migration.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_pesapalipn_alter_payment_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="duration_days",
            field=models.PositiveIntegerField(default=180),
        ),
    ]

