# Generated by Django 5.1.5 on 2026-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_move_livestream_models_state_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="access_duration",
            field=models.CharField(blank=True, default="lifetime", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="allow_self_enrollment",
            field=models.BooleanField(default=True),
        ),
    ]
