# Generated by Django 5.1.5 on 2026-02-22 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_move_livestream_models_state_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="access_duration",
            field=models.CharField(blank=True, default="lifetime", max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="allow_self_enrollment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="banner",
            field=models.URLField(
                blank=True,
                help_text="Wide banner image for the course detail page",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="certificate_on_completion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Remaining minutes within the hour (0–59)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enable_discussions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollment_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="grading_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="learning_objectives_list",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured list of learning objective strings; mirrors learning_objectives as newline-joined text",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="sequential_learning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subcategory",
            field=models.CharField(
                blank=True,
                help_text="Sub-classification within the category",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("text", "Text"),
                    ("live", "Live Session"),
                    ("document", "Document"),
                    ("html", "HTML / Rich Text"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("scorm", "SCORM Package"),
                ],
                default="video",
                max_length=20,
            ),
        ),
    ]
