# Generated by Django 5.1.5 on 2026-02-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_course_access_duration_course_allow_self_enrollment"),
        ("catalogue", "0004_course_wizard_fields"),
    ]

    operations = []
