# Generated by Django 5.1.5 on 2026-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_merge_20260225_0836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="access_duration",
            field=models.CharField(blank=True, default="lifetime", max_length=20),
        ),
    ]
