# Generated by Django 5.1.5 on 2026-03-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_alter_course_access_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="asset_bucket",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="asset_mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="asset_object_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="asset_original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="asset_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
