# Generated by Django 5.1.5 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_add_session_asset_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="content_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inline", "Inline"),
                    ("upload", "Uploaded Asset"),
                    ("external", "External Video"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="external_video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="external_video_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="external_video_embed_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
