# Generated by Django 5.1.5 on 2026-03-04

from django.db import migrations


from urllib.parse import urlparse, parse_qs
import re


def _derive_provider_embed_url(url):
    """
    Derive provider and embed URL directly inside migration
    so the migration does not depend on application code.
    """
    if not url:
        return None, None

    parsed = urlparse(url)
    if parsed.scheme != "https":
        return None, None

    host = (parsed.netloc or "").lower()
    path = (parsed.path or "").strip("/")

    # YouTube
    if "youtube.com" in host:
        qs = parse_qs(parsed.query)
        vid = (qs.get("v") or [None])[0]
        if vid:
            return "youtube", f"https://www.youtube.com/embed/{vid}"

    if "youtu.be" in host:
        vid = path.split("/")[0] if path else None
        if vid:
            return "youtube", f"https://www.youtube.com/embed/{vid}"

    # Vimeo
    if "vimeo.com" in host:
        video_id = path.split("/")[0] if path else None
        if video_id and re.match(r"^\d+$", video_id):
            return "vimeo", f"https://player.vimeo.com/video/{video_id}"

    # Loom
    if "loom.com" in host:
        parts = path.split("/")
        if "share" in parts:
            idx = parts.index("share")
            if idx + 1 < len(parts):
                embed_id = parts[idx + 1]
                return "loom", f"https://www.loom.com/embed/{embed_id}"

    return None, None


def backfill_content_source_and_external_video(apps, schema_editor):
    Session = apps.get_model("catalogue", "Session")

    for session in Session.objects.all():
        asset_key = (session.asset_object_key or "").strip()
        video_url = (session.video_url or "").strip()

        if asset_key:
            session.content_source = "upload"
            session.external_video_url = None
            session.external_video_provider = None
            session.external_video_embed_url = None
        elif video_url:
            session.content_source = "external"
            session.external_video_url = video_url
            provider, embed_url = _derive_provider_embed_url(video_url)
            session.external_video_provider = provider
            session.external_video_embed_url = embed_url
        else:
            session.content_source = "inline"
            session.external_video_url = None
            session.external_video_provider = None
            session.external_video_embed_url = None

        session.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_add_session_content_source_and_external_video_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_content_source_and_external_video, noop),
    ]
