# Generated by Django 5.1.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_backfill_session_content_source_and_external_video_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("hidden", "Hidden")], default="draft", max_length=20)),
                ("icon", models.CharField(blank=True, choices=[("play-circle", "Play Circle"), ("layer-group", "Layers"), ("puzzle-piece", "Puzzle"), ("share-alt", "Share"), ("trophy", "Trophy"), ("book", "Book"), ("code", "Code")], default="play-circle", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("require_sequential", models.BooleanField(default=False)),
                ("allow_preview", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="modules", to="catalogue.course")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(fields=("course", "order"), name="catalogue_module_course_order_unique"),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(fields=["course", "order"], name="catalogue_module_course_order_idx"),
        ),
        migrations.AddField(
            model_name="session",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="catalogue.module",
            ),
        ),
    ]
