# Generated by Django 5.1.5 on 2026-03-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_add_module_model_and_session_module_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="module",
            new_name="catalogue_m_course__fe6513_idx",
            old_name="catalogue_module_course_order_idx",
        ),
    ]
