# Generated by Django 5.1.5 on 2026-03-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0017_course_rejection_reason"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="courseapprovalrequest",
            new_name="catalogue_c_status_9b807a_idx",
            old_name="catalogue_c_status_9a8f2c_idx",
        ),
        migrations.RenameIndex(
            model_name="courseapprovalrequest",
            new_name="catalogue_c_course__c2a1e6_idx",
            old_name="catalogue_c_course__e7d5a3_idx",
        ),
    ]
