# Generated by Django 5.1.5 on 2026-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_rename_catalogue_c_status_9a8f2c_idx_catalogue_c_status_9b807a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
