# Generated by Django 5.1.5 on 2026-03-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_sessionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
