# Generated by Django 5.1.5 on 2026-03-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0021_coursereview_helpful_count_coursereview_report_count"),
        ("catalogue", "0021_remove_quizquestion_explanation_column"),
    ]

    operations = []
