# Generated by Django 5.1.5 on 2026-03-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_merge_20260328_0303"),
        ("catalogue", "0022_merge_20260328_0334"),
    ]

    operations = []
