# Generated by Django 5.1.5 on 2026-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0023_merge_20260328_2300"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
