# Generated by Django 5.1.5 on 2026-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestream", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreamsession",
            name="platform",
            field=models.CharField(
                choices=[
                    ("zoom", "Zoom"),
                    ("custom", "Custom RTMP"),
                    ("google_meet", "Google Meet"),
                    ("teams", "Microsoft Teams"),
                ],
                default="zoom",
                max_length=20,
            ),
        ),
    ]
