# Generated by Django 5.1.5 on 2026-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_alter_livestreamsession_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamsession',
            name='calendar_channel_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livestreamsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livestreamsession',
            name='teams_join_url',
            field=models.URLField(blank=True, help_text='Teams join URL'),
        ),
        migrations.AddField(
            model_name='livestreamsession',
            name='teams_meeting_id',
            field=models.CharField(blank=True, help_text='Teams online meeting ID', max_length=255),
        ),
    ]
